#!/bin/bash

# run from source directory
cd "${0%/*}"

source ./scripts/inc/utils

read -p " - format $(BOLD "all") files in $(YELLOW "src/") ? $(BOLD "(y/n): ") "  -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
  clang-format --verbose -i --style=file src/*.c
  echo
  echo " - $(GREEN "done")"
  echo
fi

read -p " - format $(BOLD "all") in $(YELLOW "include/") ? $(BOLD "(y/n): ") "  -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
  clang-format --verbose -i --style=file include/*.h
  echo
  echo " - $(GREEN "done")"
  echo
fi



