#!/bin/bash

# run from source directory
cd "${0%/*}"

source ./scripts/inc/utils

log=cppcheck.log
proj=surveysystem.cppcheck

cppcheck \
    --output-file="${log}" \
    --enable=all \
    --project="${proj}"

count=$(wc -l "${log}" | awk '{ print $1 }')
echo -e "\n$(GREEN "done") - results logged to: ${log} $(DIM "(${count} lines)")\n"
