#!/bin/bash

if [ -z ${PROPRIETARY_TEST_LOC+x} ]; then
	echo "you should set the variable PROPRIETARY_TEST_LOC to use this program, I will look for tests at ${HOME}/code/SleepCompanionREimplementation/testsWithBackend/"
	PROPRIETARY_TEST_LOC=${HOME}/code/SleepCompanionREimplementation/testsWithBackend/
fi

if [ `ls ${PROPRIETARY_TEST_LOC} -1 | wc -l` -eq 0 ]; then
	echo "I can't find any tests at ${PROPRIETARY_TEST_LOC}, I will look for tests at ${HOME}/code/SleepCompanionREimplementation/testsWithBackend/"
	PROPRIETARY_TEST_LOC=${HOME}/code/SleepCompanionREimplementation/testsWithBackend/
fi

if [ `ls ${PROPRIETARY_TEST_LOC}/*.test -1 | wc -l` -eq 0 ]; then
       echo "I can't find any tests at ${PROPRIETARY_TEST_LOC} -- I am giving up."
       exit
fi

make && sudo rm /var/www/fastcgi/surveyfcgi && sudo cp surveyfcgi /var/www/fastcgi/ && make test_runner && ./test_runner ${PROPRIETARY_TEST_LOC}/*.test
