#!/bin/bash

# include utils
source ./scripts/inc/utils

LOG=cppcheck-log.xml

# see https://github.com/rizsotto/Bear#how-to-use
echo -e "$(YELLOW "--- 1/3 make clean ---")\n"
sudo make clean

echo -e "\n$(YELLOW "--- 2/3 bear make ---")\n"
sudo bear make

# TODO error "missingInclude:Cppcheck cannot find all the include files" - might relate to "question_types.h" which is generated during maeke

if [ $? -eq 0 ]; then
    echo -e "\n$(YELLOW "--- 3/3 cppcheck ---")\n"
    cppcheck \
        --xml \
        --output-file="$LOG" \
        --enable=all \
        --project=compile_commands.json\
         src/
else 
    echo -e "\n$(RED "--- linting failed ---")\n"
    exit 1
fi

echo -e "\n$(GREEN "--- results logged to: "$LOG" ---")\n"
echo $(grep -c -- '</error>' "$LOG") errors found
