#!/bin/bash

if [ ! -d ./testlog ]; then
    mkdir ./testlog
fi
chmod -R 777 testlog

make \
&& sudo rm /var/www/fastcgi/surveyfcgi \
&& sudo cp surveyfcgi /var/www/fastcgi/ \
&& make test_runner \
&& ./test_runner tests/*.test
