#!/bin/bash

if ! command -v tmux &> /dev/null; then
    echo "tmux not installed exiting..."
    exit 1
fi

# init
source scripts/inc/utils
REQUIRE_SUDO

SESSION=ss
HERE="$(pwd)"

tmux kill-session -t "${SESSION}"

tmux start-server
tmux new-session -d -s "${SESSION}"

tmux splitw -v -p 25
tmux send-keys "sudo tail -n 1 -F /var/log/lighttpd/breakage.log" C-m

tmux splitw -v -p 50
tmux send-keys "sudo tail -n 1 -F /var/log/lighttpd/error.log" C-m

tmux splitw -v -p 75
tmux send-keys "sudo tail -n 1 -f `ls -1td logs/*| /usr/bin/head -n1`" C-m

# select top window
tmux selectp -t 0

# focus top window back to human user
tmux send-keys "su - $(logname)" C-m
tmux send-keys "cd ${HERE}" C-m
tmux send-keys "clear" C-m

tmux attach-session -t "${SESSION}"
