#!/usr/bin/env bash

# Copy file to valgrind-<your name> (see .gitignore), make it executable and adjust paths

sudo valgrind \
  --tool=memcheck \
  --leak-check=full \
  --log-file=./logs/valgrind.log \
  --trace-children=yes \
  --gen-suppressions=all \
  --suppressions=./valgrind.supp \
  env SURVEY_HOME=./ \
      SURVEY_PYTHONDIR=./python \
  ./surveycli "$@"
