#!/usr/bin/env bash

####
# flush logs
# lint script with `shellcheck -x <FILE>`
####

# variables
LOG_DIR=../logs/

# include utils
source inc/utils

REQUIRE_SUDO
REQUIRE_DIR "$LOG_DIR"

# review files to delete
find "$LOG_DIR" \( -name \*.log -o -name \*.gz \) -type f

echo ---------------
read -p "Are you sure to delete above files $(RED "(y/n) $(BLINK "?")") " -n 1 -r
echo

case $REPLY in
  Y | y)
    find "$LOG_DIR" \( -name \*.log -o -name \*.gz \) -type f -delete
    echo "$(GREEN "done")"
    ;;

  N | n)
    echo "$(YELLOW "aborted")", exiting...
    ;;

  *)
    EXIT_ERROR "unkown input: \"$REPLY\""
    ;;
esac
