#!/usr/bin/env bash

####
# flush sessions
# lint script with `shellcheck -x <FILE>`
####

# variables
SESSION_DIR="../sessions"
SURVEY_DIR="../surveys"
LOG_DIR="../logs"
LOCKS_DIR="../locks"
TESTLOG_DIR="../testlog"

# include utils
source inc/utils

REQUIRE_SUDO
REQUIRE_DIR "$SESSION_DIR"
REQUIRE_DIR "$SURVEY_DIR"
REQUIRE_DIR "$LOG_DIR"
REQUIRE_DIR "$LOCKS_DIR"
REQUIRE_DIR "$TESTLOG_DIR"

echo
echo  "-------------------------------------------"
echo  " $(RED "DO NOT RUN THIS ON PRODUCTION!")"
echo  " All session data and logs will be deleted"
echo  "-------------------------------------------"
echo

# stat & query logs
SIZE_L=$(du -sh "$LOG_DIR" | awk '{print $1}')
COUNT_L=$(ls -l "$LOG_DIR" | grep ^- | wc -l)
echo "$(BOLD "$COUNT_L logs found"): $SIZE_L"
read -p " - Flush all logs $(BOLD "(y/n) $(BLINK "?")") "  -n 1 -r DO_LOGS
echo

# flush logs
if [ "$DO_LOGS" == "y" ]; then
    find "${LOG_DIR:?}" -mindepth 1 ! -name '.git*' ! -name '*.md' -delete
    echo "-- done"
fi

#-------

# stat & query testlogs
SIZE_T=$(du -sh "$TESTLOG_DIR" | awk '{print $1}')
COUNT_T=$(ls -l "$TESTLOG_DIR" | grep ^- | wc -l)
echo "$(BOLD "$COUNT_T test logs found"): $SIZE_T"
read -p " - Flush all test logs $(BOLD "(y/n) $(BLINK "?")") "  -n 1 -r DO_TESTLOGS
echo

# flush testlogs
if [ "$DO_TESTLOGS" == "y" ]; then
    find "${TESTLOG_DIR:?}" -mindepth 1 ! -name '.git*' ! -name '*.md' -delete
    echo "-- done"
fi

#-------

# stat & query session locks
SIZE_F=$(du -sh "$LOCKS_DIR" | awk '{print $1}')
COUNT_F=$(ls -l "$LOCKS_DIR" | grep ^d | wc -l)
echo "$(BOLD "$COUNT_F lock files found"): $SIZE_F"
read -p " - Flush all lock files $(BOLD "(y/n) $(BLINK "?")") "  -n 1 -r DO_LOCKS
echo

# flush lock files
if [ "$DO_LOCKS" == "y" ]; then
    find "${LOCKS_DIR:?}" -mindepth 1 ! -name '.git*' ! -name '*.md' -delete
    echo "-- done"
fi

#-------

# stat & query sessions
SIZE_S=$(du -sh "$SESSION_DIR" | awk '{print $1}')
COUNT_S=$(ls -l "$SESSION_DIR" | grep ^d | wc -l)
echo "$(BOLD "$COUNT_S sessions found"): $SIZE_S"
read -p " - Flush all $(RED "sessions") $(BOLD "(y/n) $(BLINK "?")") "  -n 1 -r DO_SESSIONS
echo

# flush sessions
if [ "$DO_SESSIONS" == "y" ]; then
    find "${SESSION_DIR:?}" -mindepth 1 ! -name '.git*' ! -name '*.md' -delete
    echo "-- done"
fi
#-------

# stat & query survey hashs
SIZE_S=$(du -sh "$SURVEY_DIR" | awk '{print $1}')
COUNT_S=$(find "${SURVEY_DIR:?}" -mindepth 1 -type f ! -name 'current' ! -name '.git*' ! -name '*.md' | wc -l)
echo "$(BOLD "$COUNT_S hashed survey copies found"): $SIZE_S"
read -p " - Flush all $(RED "survey copies") $(BOLD "(y/n) $(BLINK "?")") "  -n 1 -r DO_SURVEYS
echo

# flush survey hashs
if [ "$DO_SURVEYS" == "y" ]; then
    find "${SURVEY_DIR:?}" -mindepth 1 -type f ! -name 'current' ! -name '.git*' ! -name '*.md' -delete
    echo "-- done"
fi

# done
echo ---------------
GREEN "done"

