#!/usr/bin/env bash

####
## HARD kills a given port synchronously
## NOTE: This script is invoked by by test_runner, thus any changes here may break it's behaviour
####

if [ $UID != 0 ]; then
    printf "Please run this script as sudo"
    exit 1
fi

if [ -z "$1" ]; then
    printf "Error: port required"
    exit 1
fi

PID=$(lsof -t -i:"${1}")

if [ -z "${PID}" ]; then
    printf "skip: no pid"
    exit 0
fi

if kill -0 "${PID}" && kill -SIGKILL "${PID}"; then
    printf "Error killing %d(%s)" "${1}" "${PID}"
    exit 1
fi

while kill -0 "${PID}" > /dev/null 2>&1; do
    sleep 1
done
sleep 1
printf "killed %d(%s)" "${1}" "${PID}"
